version: "3.9"

services:
  app:
    build: .
    image: ecoisland-java-app
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3307:3306"

networks:
  default:
    name: ecoisland-network
